title: Smørfugl
description: Smørfugl's theme
baseurl: ""
url: https://chrisjust.github.io

theme: cvless

# site settings
taglong: Senior Platform Engineer
tagshort: Smørfugl, smoerfugl.dk
cv: true

# author settings
author:
  name: Chris Justesen
  email: chris@smoerfugl.dk
photo: assets/files/photo.jpg
address: Åbakken 5, 4700 Næstved, Denmark
phone: +45 28 97 62 30

# profile links
profile:
  facebook: https://www.facebook.com/chris.justesen
  linkedin: https://www.linkedin.com/in/chris-just
  github: https://github.com/chrisjust
  github: https://github.com/smoerfugl

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
